### ISSUE TITLE
one way it works

### ISSUE THREAD

**Issue by psytraxx** [doughock/aws_ec2_test#1]
hi there - 
i am experiencing the same problems on my project
i am not sure if it helps - 
but when i run ionic run android -c -s -l -r - i wont get the error - 
it look like running the command instead of ionic run android  seems to send the aws request from the local machine / proxy instread of the connected device
i have tried everything - from cordova whitlist plugin to 
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src *; img-src 'self' localhost; style-src 'self' 'unsafe-inline';font-src 'self' localhost;">

using AWS.config.logger = console; did also give no reason of the error

**Comment by doughock** [comment]
Thanks for the reply.  From your description, we both seem to be experiencing the same issue.  I have a post on Amazon's forum (https://forums.aws.amazon.com/thread.jspa?threadID=218888&tstart=0), but no response yet from the community or Amazon dev team.

I will keep you posted.

**Comment by psytraxx** [comment]
great - i just did a test with s3 and it works flawless - seems to be really a aws ec2 endpoint problem

**Comment by doughock** [comment]
Thanks for the update.  Interesting that the S3 service is reachable.  I posted another message on the AWS forums requesting the Amazon SDK dev team assist.  Hopefully we will get a response.

**Comment by doughock** [comment]
Had someone from Amazon reply to the post on AWS forums.  They are looking into this item.  Hopefully we will get some resolution soon.

**Comment by psytraxx** [comment]
great ! thanks for the update

**Comment by doughock** [comment]
I have not heard back from he Amazon developer.  Have you made any progress on getting the EC2 calls to work from the devices?

**Comment by psytraxx** [comment]
Hi, no I didnt - i thing i will move the logic eventually to the server and consume it through my own api.

**Comment by doughock** [comment]
thanks for your update.  Good luck with your efforts.
